[project]
name = "dynamic-pricing"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "networkx>=3.6.1",
    "numpy>=2.4.1",
    "scikit-fuzzy>=0.5.0",
    "scipy>=1.17.0",
]
